storage:
  aws:
    kind: aws_s3
    bucket: downloads.dcos.io
    object_prefix: dcos/dcos-windows
    download_url: https://downloads.dcos.io/dcos/dcos-windows/
  azure:
    kind: azure_block_blob
    account_name: $AZURE_PROD_STORAGE_ACCOUNT
    account_key: $AZURE_PROD_STORAGE_ACCESS_KEY
    container: dcos
    download_url: https://dcosio.azureedge.net/dcos/dcos-windows/
options:
  preferred: azure
