root:
  - path: /etc/mesosphere/setup-flags/repository-url
    permissions: "0644"
    owner: root
    content: |
      {{ bootstrap_url }}
  - path: /etc/mesosphere/setup-flags/bootstrap-id
    permissions: "0644"
    owner: root
    content: |
      BOOTSTRAP_ID={{ bootstrap_id }}
  - path: /etc/mesosphere/setup-flags/cluster-packages.json
    permissions: "0644"
    owner: root
    content: |
      {{ cluster_packages }}
  - path: /etc/systemd/journald.conf.d/dcos.conf
    permissions: "0644"
    owner: root
    content: |
      [Journal]
      MaxLevelConsole=warning
      RateLimitInterval=1s
      RateLimitBurst=20000
  - path: /etc/rexray/config.yml
    permissions: "0644"
    content: {{ rexray_config_contents }}
